stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/rf_model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/rf_model.pkl
    - src/model/model_evaluation.py
    metrics:
    - results/result_metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
